# server/docker-compose.yml
#version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SEED_USER: ${SEED_USER}
      SEED_USER_PASSWORD: ${SEED_USER_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  seed:
    image: node:20
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    command: >
      bash -c "
      until (echo > /dev/tcp/db/5432) >/dev/null 2>&1; do
        echo '⏳ Waiting for db...';
        sleep 1;
      done &&
      echo '✅ DB is up!' &&
      npm install &&
      npx prisma generate &&
      npx prisma db push &&
      npx prisma db seed -- --environment $NODE_ENV
      "

volumes:
  pgdata: